#
# EcoAddon
# by mani123
#
# Blast furnace crafts
enableBlastingRecipe: true
# Campfire crafts
enableCampfireRecipe: true
# StoneCutter crafts
enableStoneCutter: true
# Furnace crafts
enableFurnaceRecipe: true
# Smithing table crafts
enableSmithingRecipe: true
# Smoker crafts
enableSmokingRecipe: true
#
enableVillagerRecipe: false # soon