#
# EcoAddon
# by mani123
#
#
enableBlastingRecipe: false # soon
#
enableCampfireRecipe: true
#
enableCookingRecipe: false # soon
#
enableFurnaceRecipe: true
#
enableSmithingRecipe: false # soon
#
enableSmokingRecipe: true
#
enableStoneCutter: true