#
# EcoAddon
# by mani123
#
#
enableBlastingRecipe: true
#
enableCampfireRecipe: true
#
enableStoneCutter: true
#
enableFurnaceRecipe: true
#
enableSmithingRecipe: true
#
enableSmokingRecipe: true
#
enableCookingRecipe: false # soon